### ISSUE TITLE
render three times

### ISSUE THREAD

**Issue by Liripo** [plotly/dash-component-boilerplate#158]
Use_async as a template for development and initialize rendering three times.
![image](https://github.com/plotly/dash-component-boilerplate/assets/54770415/d6549d4c-c983-4865-8b7c-79397fb8830d)

![image](https://github.com/plotly/dash-component-boilerplate/assets/54770415/b1ae41b3-e700-4c36-a3f5-f603e93dc64a)

I transferred the simple sample repository code to [Google Drive](https://drive.google.com/file/d/1P9WDygQtggTYTGyscp1FJmyoZPnyg7e6/view?usp=drive_link).

**Comment by alexcjohnson** [comment]
This is typical, there should be different props each time - once with its initial state, a second time with a `loading_state` when the callback has been queued, and the final time with the callback result.

We could probably find a way to skip `loading_state` when your component isn't using it but the other two are required since you have the component hooked up to a callback and you're not using `prevent_initial_call=True`.

**Comment by Liripo** [comment]
Thank you.
